---
#==============================================================#
# File      :   pigsty.yml (generated by pigsty-v2)
# Desc      :   Pigsty configuration for self-hosting Supabase
# Template  :   v2/config/pigsty.yml.tpl
#==============================================================#

all:
  children:

    #----------------------------------------------#
    # INFRA
    #----------------------------------------------#
    infra:
      hosts:
        ${META_IP}: { infra_seq: 1 }
      vars:
        repo_enabled: false

    #----------------------------------------------#
    # ETCD
    #----------------------------------------------#
    etcd:
      hosts:
        ${META_IP}: { etcd_seq: 1 }
      vars:
        etcd_cluster: etcd
        etcd_safeguard: false

    #----------------------------------------------#
    # MINIO
    #----------------------------------------------#
    minio:
      hosts:
        ${META_IP}: { minio_seq: 1 }
      vars:
        minio_cluster: minio
        minio_users:
          - { access_key: pgbackrest  ,secret_key: S3User.Backup ,policy: pgsql }
          - { access_key: s3user_meta ,secret_key: S3User.Meta   ,policy: meta  }
          - { access_key: s3user_data ,secret_key: S3User.Data   ,policy: data  }

    #----------------------------------------------#
    # PostgreSQL cluster for Supabase
    #----------------------------------------------#
    ${PG_CLUSTER_NAME}:
      hosts:
        ${META_IP}: { pg_seq: 1, pg_role: primary }
      vars:
        pg_cluster: ${PG_CLUSTER_NAME}
        pg_users:
          - { name: anon           ,login: false }
          - { name: authenticated  ,login: false }
          - { name: dashboard_user ,login: false ,replication: true ,createdb: true ,createrole: true }
          - { name: service_role   ,login: false ,bypassrls: true }
          - { name: supabase_admin             ,password: '${SUPABASE_DB_PASSWORD}' ,pgbouncer: true ,inherit: true   ,roles: [ dbrole_admin ] ,superuser: true ,replication: true ,createdb: true ,createrole: true ,bypassrls: true }
          - { name: authenticator              ,password: '${SUPABASE_DB_PASSWORD}' ,pgbouncer: true ,inherit: false  ,roles: [ dbrole_admin, authenticated ,anon ,service_role ] }
          - { name: supabase_auth_admin        ,password: '${SUPABASE_DB_PASSWORD}' ,pgbouncer: true ,inherit: false  ,roles: [ dbrole_admin ] ,createrole: true }
          - { name: supabase_storage_admin     ,password: '${SUPABASE_DB_PASSWORD}' ,pgbouncer: true ,inherit: false  ,roles: [ dbrole_admin, authenticated ,anon ,service_role ] ,createrole: true }
          - { name: supabase_functions_admin   ,password: '${SUPABASE_DB_PASSWORD}' ,pgbouncer: true ,inherit: false  ,roles: [ dbrole_admin ] ,createrole: true }
          - { name: supabase_replication_admin ,password: '${SUPABASE_DB_PASSWORD}' ,replication: true ,roles: [ dbrole_admin ]}
          - { name: supabase_etl_admin         ,password: '${SUPABASE_DB_PASSWORD}' ,replication: true ,roles: [ pg_read_all_data, dbrole_readonly ]}
          - { name: supabase_read_only_user    ,password: '${SUPABASE_DB_PASSWORD}' ,bypassrls: true ,roles:   [ pg_read_all_data, dbrole_readonly ]}

        pg_databases:
          - name: postgres
            baseline: supabase.sql
            owner: supabase_admin
            comment: supabase postgres database
            schemas: [ extensions ,auth ,realtime ,storage ,graphql_public ,supabase_functions ,_analytics ,_realtime ]
            extensions:
              - { name: pgcrypto         ,schema: extensions }
              - { name: pg_net           ,schema: extensions }
              - { name: pgjwt            ,schema: extensions }
              - { name: uuid-ossp        ,schema: extensions }
              - { name: pgsodium         ,schema: extensions }
              - { name: supabase_vault   ,schema: extensions }
              - { name: pg_graphql       ,schema: extensions }
              - { name: pg_jsonschema    ,schema: extensions }
              - { name: wrappers         ,schema: extensions }
              - { name: http             ,schema: extensions }
              - { name: pg_cron          ,schema: extensions }
              - { name: timescaledb      ,schema: extensions }
              - { name: pg_tle           ,schema: extensions }
              - { name: vector           ,schema: extensions }
              - { name: pgmq             ,schema: extensions }
          - { name: supabase ,owner: supabase_admin ,comment: supabase analytics database ,schemas: [ extensions, _analytics ] }

        pg_libs: 'timescaledb, pgsodium, plpgsql, plpgsql_check, pg_cron, pg_net, pg_stat_statements, auto_explain, pg_wait_sampling, pg_tle, plan_filter'
        pg_extensions: [ pg${PG_VERSION}-main ,pg${PG_VERSION}-time ,pg${PG_VERSION}-gis ,pg${PG_VERSION}-rag ,pg${PG_VERSION}-fts ,pg${PG_VERSION}-olap ,pg${PG_VERSION}-feat ,pg${PG_VERSION}-lang ,pg${PG_VERSION}-type ,pg${PG_VERSION}-util ,pg${PG_VERSION}-func ,pg${PG_VERSION}-admin ,pg${PG_VERSION}-stat ,pg${PG_VERSION}-sec ,pg${PG_VERSION}-fdw ,pg${PG_VERSION}-sim ,pg${PG_VERSION}-etl]
        pg_parameters: { cron.database_name: postgres }
        pg_hba_rules:
          - { user: all ,db: postgres  ,addr: intra         ,auth: pwd ,title: 'allow supabase access from intranet'    ,order: 50 }
          - { user: all ,db: all       ,addr: admin         ,auth: pwd ,title: allow supabase through local haproxy ,order: 50 }
          - { user: all ,db: postgres  ,addr: 172.17.0.0/16 ,auth: pwd ,title: 'allow access from local docker network' ,order: 50 }
        pg_crontab:
          - '00 01 * * * /pg/bin/pg-backup full'
          - '*  *  * * * /pg/bin/supa-kick'

    # Supabase (Docker)
    #----------------------------------------------#
    supabase:
      hosts:
        ${META_IP}: {}
      vars:
        docker_enabled: true
        app: supabase
        apps:
          supabase:
            conf:
              JWT_SECRET: ${JWT_SECRET}
              ANON_KEY: ${ANON_KEY}
              SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
              PG_META_CRYPTO_KEY: ${PG_META_CRYPTO_KEY}
              DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
              DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
              LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_PUBLIC_ACCESS_TOKEN}
              LOGFLARE_PRIVATE_ACCESS_TOKEN: ${LOGFLARE_PRIVATE_ACCESS_TOKEN}
              POSTGRES_HOST: ${META_PRIVATE_IP}
              POSTGRES_PORT: 5436
              POSTGRES_DB: postgres
              POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
              SITE_URL: https://${APP_FQDN}
              API_EXTERNAL_URL: https://${API_FQDN}
              SUPABASE_PUBLIC_URL: https://${APP_FQDN}
              S3_BUCKET: ${S3_BUCKET}
              S3_ENDPOINT: ${S3_ENDPOINT}
              S3_ACCESS_KEY: ${S3_ACCESS_KEY}
              S3_SECRET_KEY: ${S3_SECRET_KEY}
              S3_FORCE_PATH_STYLE: true
              S3_PROTOCOL: https
              S3_REGION: ${S3_REGION}
              S3_PROTOCOL_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
              S3_PROTOCOL_ACCESS_KEY_SECRET: ${S3_SECRET_KEY}
              MINIO_DOMAIN_IP: ${META_IP}
              SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
              SMTP_HOST: ${SMTP_HOST}
              SMTP_PORT: ${SMTP_PORT}
              SMTP_USER: ${SMTP_USER}
              SMTP_PASS: ${SMTP_PASS}
              SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
              ENABLE_ANONYMOUS_USERS: false
          registry:
            file:
              - { path: /data/registry ,state: directory ,mode: 0755 }
            conf:
              REGISTRY_DATA: /data/registry
              REGISTRY_PORT: 5000
              REGISTRY_UI_PORT: 5080
              REGISTRY_STORAGE_DELETE_ENABLED: true
              REGISTRY_LOG_LEVEL: info

  #==============================================================#
  # Global Parameters
  #==============================================================#
  vars:
    version: ${PIGSTY_VERSION}
    admin_ip: ${META_IP}
    region: default
    proxy_env:
      no_proxy: "localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,*.pigsty,*.aliyun.com,mirrors.*,*.myqcloud.com,*.tsinghua.edu.cn"

    certbot_sign: false
    certbot_email: ${CERTBOT_EMAIL}

    infra_portal:
      home      : { domain: ${PORTAL_FQDN} }
      pgadmin   : { domain: adm.pigsty ,endpoint: "${META_IP}:8885" }
      bytebase  : { domain: ddl.pigsty ,endpoint: "${META_IP}:8887" }
      supabase-api:
        domain: ${API_FQDN}
        endpoint: "${META_IP}:8000"
        websocket: true
        certbot: ${API_FQDN}
      supabase:
        domain: ${STUDIO_FQDN}
        endpoint: "${META_IP}:3001"
        websocket: true
        certbot: ${STUDIO_FQDN}
      neura-core:
        domain: ${APP_FQDN}
        endpoint: "127.0.0.1:8081"
        certbot: ${APP_FQDN}
      neura-pos:
        domain: ${POS_FQDN}
        endpoint: "127.0.0.1:8082"
        certbot: ${POS_FQDN}
      neura-ai:
        domain: ${AI_FQDN}
        endpoint: "127.0.0.1:3003"
        websocket: true
        certbot: ${AI_FQDN}
      # LiteLLM stays internal on 127.0.0.1:4000 and is consumed by flare-server.
      # Docker registry stays private on localhost:5000 and localhost:5080.
      supa:
        domain: supa.pigsty
        endpoint: "${META_IP}:8000"
        websocket: true

    #----------------------------------------------#
    # NODE
    #----------------------------------------------#
    nodename_overwrite: false
    node_tune: tiny
    node_etc_hosts:
      - ${META_IP} i.pigsty sss.pigsty supa.pigsty ${PORTAL_FQDN} ${APP_FQDN} ${POS_FQDN} ${AI_FQDN} ${API_FQDN} ${STUDIO_FQDN} ${REGISTRY_FQDN} ${REGISTRY_UI_FQDN}
    node_repo_modules: node,pgsql,infra
    node_repo_remove: true

    #----------------------------------------------#
    # PGSQL
    #----------------------------------------------#
    pg_version: ${PG_VERSION}
    pg_locale: C.UTF-8
    pg_lc_collate: C.UTF-8
    pg_lc_ctype: C.UTF-8
    pg_conf: tiny.yml
    pg_safeguard: false
    pg_default_schemas: [ monitor, extensions ]
    pg_default_extensions:
      - { name: pg_stat_statements ,schema: monitor     }
      - { name: pgstattuple        ,schema: monitor     }
      - { name: pg_buffercache     ,schema: monitor     }
      - { name: pageinspect        ,schema: monitor     }
      - { name: pg_prewarm         ,schema: monitor     }
      - { name: pg_visibility      ,schema: monitor     }
      - { name: pg_freespacemap    ,schema: monitor     }
      - { name: pg_wait_sampling   ,schema: monitor     }
      - { name: postgres_fdw       ,schema: extensions  }
      - { name: file_fdw           ,schema: extensions  }
      - { name: btree_gist         ,schema: extensions  }
      - { name: btree_gin          ,schema: extensions  }
      - { name: pg_trgm            ,schema: extensions  }
      - { name: intagg             ,schema: extensions  }
      - { name: intarray           ,schema: extensions  }
      - { name: pg_repack          ,schema: extensions  }

    #----------------------------------------------#
    # BACKUP
    #----------------------------------------------#
    minio_endpoint: https://sss.pigsty:9000
    pgbackrest_method: minio
    pgbackrest_repo:
      local:
        path: /pg/backup
        retention_full_type: count
        retention_full: 2
      minio:
        type: s3
        s3_endpoint: sss.pigsty
        s3_region: us-east-1
        s3_bucket: pgsql
        s3_key: pgbackrest
        s3_key_secret: S3User.Backup
        s3_uri_style: path
        path: /pgbackrest
        storage_port: 9000
        storage_ca_file: /etc/pki/ca.crt
        block: y
        bundle: y
        bundle_limit: 20MiB
        bundle_size: 128MiB
        cipher_type: aes-256-cbc
        cipher_pass: ${PGBACKREST_CIPHER_PASS}
        retention_full_type: time
        retention_full: 14

    #----------------------------------------------#
    # PASSWORDS
    #----------------------------------------------#
    grafana_admin_password: ${GRAFANA_ADMIN_PASSWORD}
    grafana_view_password: DBUser.Viewer
    pg_admin_password: ${PG_ADMIN_PASSWORD}
    pg_monitor_password: ${PG_MONITOR_PASSWORD}
    pg_replication_password: ${PG_REPLICATION_PASSWORD}
    patroni_password: ${PATRONI_PASSWORD}
    haproxy_admin_password: ${HAPROXY_ADMIN_PASSWORD}
    minio_secret_key: S3User.MinIO
    etcd_root_password: ${ETCD_ROOT_PASSWORD}
...
